import municipalityByDistrictData from "./municipalityByDistrict.json";
import municipalityWardNumbersData from "./municipalityWardNumbers.json";

const legacyDistrictOptions = [
  "Achham",
  "Arghakhanchi",
  "Baglung",
  "Baitadi",
  "Bajhang",
  "Bajura",
  "Banke",
  "Bara",
  "Bardiya",
  "Bhaktapur",
  "Bhojpur",
  "Chitwan",
  "Dadeldhura",
  "Dailekh",
  "Dang",
  "Darchula",
  "Dhading",
  "Dhankuta",
  "Dhanusha",
  "Dolakha",
  "Dolpa",
  "Doti",
  "Gorkha",
  "Gulmi",
  "Humla",
  "Ilam",
  "Jajarkot",
  "Jhapa",
  "Jumla",
  "Kailali",
  "Kalikot",
  "Kanchanpur",
  "Kapilvastu",
  "Kaski",
  "Kathmandu",
  "Kavrepalanchok",
  "Khotang",
  "Lalitpur",
  "Lamjung",
  "Mahottari",
  "Makwanpur",
  "Manang",
  "Morang",
  "Mugu",
  "Mustang",
  "Myagdi",
  "Nawalpur",
  "Nuwakot",
  "Okhaldhunga",
  "Palpa",
  "Panchthar",
  "Parasi",
  "Parbat",
  "Parsa",
  "Pyuthan",
  "Ramechhap",
  "Rasuwa",
  "Rautahat",
  "Rolpa",
  "Rukum East",
  "Rukum West",
  "Rupandehi",
  "Salyan",
  "Sankhuwasabha",
  "Saptari",
  "Sarlahi",
  "Sindhuli",
  "Sindhupalchok",
  "Siraha",
  "Solukhumbu",
  "Sunsari",
  "Surkhet",
  "Syangja",
  "Tanahun",
  "Taplejung",
  "Terhathum",
  "Udayapur",
];

const legacyMunicipalityOptions = [
  "Phungling",
  "Phaktanlung",
  "Mikwakhola",
  "Sirijanga",
  "Meringden",
  "Maiwakhola",
  "Aatharai Tribeni",
  "Pathivara Yangwarak",
  "Sidingba",
  "Phidim",
  "Hilihan",
  "Yangbarak",
  "Falelung",
  "Kummayak",
  "Falgunanda",
  "Tumbewa",
  "Miklajung",
  "Deumai",
  "Illam",
  "Suryodaya",
  "Mai",
  "Fakfokathum",
  "Sandakpur",
  "Mai Jogmai",
  "Chulachuli",
  "Mangsebung",
  "Rong",
  "Damak",
  "Shivasatakshi",
  "Kankai",
  "Arjundhara",
  "Mechinagar",
  "Gauradaha",
  "Birtamod",
  "Bhadrapur",
  "Kamal",
  "Buddhashanti",
  "Gauriganj",
  "Jhapa",
  "Barhadashi",
  "Haldibari",
  "Kachanakawal",
  "Biratnagar",
  "Letang",
  "Sundarharaicha",
  "Belbari",
  "Pathari Shanishchare",
  "Urlabari",
  "Rangeli",
  "Sunwarshi",
  "Ratuwamai",
  "Kerabari",
  "Kanepokhari",
  "Budhiganga",
  "Gramthan",
  "Katahari",
  "Jahada",
  "Dhanapalthan",
  "Dharan",
  "Itahari",
  "Barahachhetra",
  "Ramdhuni",
  "Inaruwa",
  "Duhabi",
  "Koshi",
  "Bhokraha Narsingh",
  "Gadhi",
  "Harinagar",
  "Dewangunj",
  "Barju",
  "Koshi Tappu",
  "Mahalaxmi",
  "Pakhribas",
  "Dhankuta",
  "Shahidbhumi",
  "Chhathar Jorpati",
  "Sangurigadhi",
  "Chaubise",
  "Laligurans",
  "Myanglung",
  "Menchhayayem",
  "Phedap",
  "Aatharai",
  "Chhathar",
  "Khandabari",
  "Panchakhapan",
  "Chainapur",
  "Dharmadevi",
  "Madi",
  "Makalu",
  "Bhotkhola",
  "Silichong",
  "Chichila",
  "Sabhapokhari",
  "Shadananda",
  "Bhojpur",
  "Salpa Silichho",
  "Temkemaiyum",
  "Arun",
  "Ramprasad Rai",
  "Pauwa Dunma",
  "Aamchowk",
  "Hatuwagadhi",
  "Solu Dhudhakunda",
  "Khumbu Pasanglhamu",
  "Mahakulung",
  "Likhu Pike",
  "Mapya Dudhkoshi",
  "Necha Salyan",
  "Thulung Dudhkoshi",
  "Sotang",
  "Halesi Tuwachung",
  "Diktel Rupakot Majhuwagadhi",
  "Aiselukharka",
  "Kepilasgadhi",
  "Rawa Besi",
  "Diprung Chuichumma",
  "Sakela",
  "Khotehang",
  "Baraha Pokhari",
  "Jante Dhunga",
  "Siddhicharan",
  "Khiji Demba",
  "Likhu",
  "Molung",
  "Champadevi",
  "Sunkoshi",
  "Chishankhu Gadhi",
  "Manebhanjyang",
  "Katari",
  "Triyuga",
  "Chaudandigadhi",
  "Belaka",
  "Tapli",
  "Limchunbung",
  "Udayapurgadhi",
  "Rautamai",
  "Surunga",
  "Khadak",
  "Shambhunath",
  "Saptakoshi",
  "Kanchanrup",
  "Bode Barsain",
  "Dakneshwori",
  "Rajbiraj",
  "Hanumannagar Kankalini",
  "Rupani",
  "Agnisair Krishna Sabaran",
  "Tirahut",
  "Balan-Bihul",
  "Mahadewa",
  "Rajgadh",
  "Bishnupur",
  "Chhinnamasta",
  "Tilathi Koiladi",
  "Karjanha",
  "Mirchaiya",
  "Golbazar",
  "Dhangadhimai",
  "Lahan",
  "Kalyanpur",
  "Sukhipur",
  "Siraha",
  "Naraha",
  "Arnama",
  "Aurahi",
  "Bariyarpatti",
  "Laxmipur Patari",
  "Nawarajpur",
  "Sakhuwa Nankarkatti",
  "Bhagawanpur",
  "Janakpurdham",
  "Mithila",
  "Ganeshman Charnath",
  "Chhireshwornath",
  "Dhanushadham",
  "Mithila Bihari",
  "Sabaila",
  "Hansapur",
  "Shahidnagar",
  "Nagarain",
  "Bideha",
  "Kamala",
  "Bateshwor",
  "Laxminiya",
  "Dhanauji",
  "Mukhiyapatti Musaharmiya",
  "Janak Nandini",
  "Bardibas",
  "Gaushala",
  "Bhangaha",
  "Ram Gopalpur",
  "Manara Shisawa",
  "Balawa",
  "Loharpatti",
  "Jaleshwor",
  "Matihani",
  "Sonama",
  "Samsi",
  "Ekadara",
  "Mahottari",
  "Pipara",
  "Bagmati",
  "Hariwan",
  "Lalbandi",
  "Barahathawa",
  "Haripur",
  "Ishworpur",
  "Kabilashi",
  "Godaita",
  "Malangawa",
  "Haripurwa",
  "Balara",
  "Basbariya",
  "Chandranagar",
  "Dhanakaul",
  "Chakraghatta",
  "Ramnagar",
  "Kaudena",
  "Brahmapuri",
  "Bishnu",
  "Parsa",
  "Gujara",
  "Chandrapur",
  "Phatuwa Bijayapur",
  "Katahariya",
  "Brindaban",
  "Maulapur",
  "Dewahi Gonahi",
  "Garuda",
  "Gadhimai",
  "Boudhimai",
  "Madhav Narayan",
  "Paroha",
  "Ishanath",
  "Rajpur",
  "Gaur",
  "Rajdevi",
  "Yamunamai",
  "Durga Bhagawati",
  "Jitpur Simara",
  "Kalaiya",
  "Nijagadh",
  "Kolhabi",
  "Mahagadhimai",
  "Pacharauta",
  "Simroungadh",
  "Parawanipur",
  "Prasauni",
  "Karaiyamai",
  "Bishrampur",
  "Pheta",
  "Baragadhi",
  "Devtal",
  "Subarna",
  "Aadarsha Kotwal",
  "Birgunj",
  "Pokhariya",
  "Bahudarmai",
  "Parsagadhi",
  "Thori",
  "Jirabhawani",
  "Paterwa Sugauli",
  "Sakhuwa Prasauni",
  "Jagarnathpur",
  "Dhobini",
  "Chhipaharmai",
  "Kalikamai",
  "Pakaha Mainpur",
  "Bindabasini",
  "Chitawan",
  "Kamalamai",
  "Dudhouli",
  "Hariharpurgaghi",
  "Marin",
  "Ghyanglekha",
  "Golanjor",
  "Tinpatan",
  "Phikkal",
  "Manthali",
  "Ramechhap",
  "Sunapati",
  "Doramba",
  "Gokulganga",
  "Umakunda",
  "Khandadevi",
  "Likhu Tamakoshi",
  "Bhimeshwor",
  "Jiri",
  "Bigu",
  "Gaurishankar",
  "Kalinchowk",
  "Baiteshwor",
  "Shailung",
  "Melung",
  "Tamakoshi",
  "Melamchi",
  "Choutara Sangachowkgadhi",
  "Bahrabise",
  "Helambu",
  "Panchpokhari Thangpal",
  "Jugal",
  "Bhotekoshi",
  "Indrawoti",
  "Balephi",
  "Tripurasundari",
  "Lisankhu Pakhar",
  "Mandan Deupur",
  "Banepa",
  "Dhulikhel",
  "Panchkhal",
  "Panauti",
  "Namobuddha",
  "Bhumlu",
  "Chauri Deurali",
  "Bethanchowk",
  "Roshi",
  "Temal",
  "Khanikhola",
  "Mahabharat",
  "Lalitpur",
  "Godawari",
  "Konjyosom",
  "Mahankal",
  "Madhyapur Thimi",
  "Changunarayan",
  "Bhaktapur",
  "Suryabinayak",
  "Kathmandu",
  "Tarakeshwor",
  "Tokha",
  "Budhanilkhantha",
  "Gokarneshwor",
  "Nagarjun",
  "Kageshwori Manahara",
  "Shankharapur",
  "Chandragiri",
  "Kirtipur",
  "Dakshinkali",
  "Bidur",
  "Belkotgadhi",
  "Myagang",
  "Kispang",
  "Suryagadhi",
  "Tadi",
  "Panchakanya",
  "Dupcheshwor",
  "Kakani",
  "Shivapuri",
  "Langtang",
  "Aamachhodingmo",
  "Gosaikunda",
  "Uttargaya",
  "Kalika",
  "Naukunda",
  "Nilkhantha",
  "Dhunibenshi",
  "Rubi Valley",
  "Ganga Jamuna",
  "Khaniyabas",
  "Netrawati Dabjong",
  "Jwalamukhi",
  "Siddhalek",
  "Benighat Rorang",
  "Gajuri",
  "Galchhi",
  "Thakre",
  "Hetauda",
  "Thaha",
  "Manahari",
  "Raksirang",
  "Kailash",
  "Bhimphedi",
  "Indrasarowar",
  "Makawanpurgadhi",
  "Bakaiya",
  "Bharatpur",
  "Ratnanagar",
  "Khairahani",
  "Rapti",
  "Ichchha Kamana",
  "Palungtar",
  "Gorkha",
  "Chumanubri",
  "Ajirkot",
  "Barpak Sulikot",
  "Dharche",
  "Siranchowk",
  "Aarughat",
  "Bhimsenthapa",
  "Shahid Lakhan",
  "Gandaki",
  "Madhya Nepal",
  "Bensishahar",
  "Sundarbazar",
  "Rainas",
  "Kwhola Sothar",
  "Marshyangdi",
  "Dordi",
  "Dudhapokhari",
  "Ngisyang",
  "Narpa Bhumi",
  "Chame",
  "Nason",
  "Pokhara",
  "Annapurna",
  "Machhapuchchhre",
  "Rupa",
  "Shuklagandaki",
  "Byas",
  "Bhanu",
  "Bhimad",
  "Myagde",
  "Ghiring",
  "Rhishing",
  "Bandipur",
  "Aanbu Khaireni",
  "Devghat",
  "Putalibazar",
  "Bhirkot",
  "Galyang",
  "Walling",
  "Chapakot",
  "Aandhikhola",
  "Phedikhola",
  "Arjun Choupari",
  "Biruwa",
  "Harinas",
  "Kaligandaki",
  "Kushma",
  "Phalebas",
  "Jaljala",
  "Modi",
  "Bihadi",
  "Mahashila",
  "Paiyu",
  "Dhorpatan",
  "Galkot",
  "Baglung",
  "Jaimuni",
  "Nisikhola",
  "Tamankhola",
  "Badigad",
  "Tarakhola",
  "Kathekhola",
  "Bareng",
  "Beni",
  "Dhawalagiri",
  "Raghuganga",
  "Malika",
  "Mangala",
  "Lomanthang",
  "Lo Ghekar Damodarkunda",
  "Varagung Muktichhetra",
  "Gharpajhong",
  "Thasang",
  "Madhya Bindu",
  "Kawasoti",
  "Devchuli",
  "Gaidakot",
  "Baudikali",
  "Bulingtar",
  "Hupsekot",
  "Binayi Tribeni",
  "Tansen",
  "Rampur",
  "Rainadevi Chhahara",
  "Tinau",
  "Ribdikot",
  "Mathagadhi",
  "Baganaskali",
  "Purbakhola",
  "Rambha",
  "Nisdi",
  "Sunawal",
  "Bardaghat",
  "Ramgram",
  "Palhinandan",
  "Sarawal",
  "Pratapapur",
  "Susta",
  "Butwal",
  "Sainamaina",
  "Devdaha",
  "Tilottama",
  "Lumbini Sanskritik",
  "Siddharthanagar",
  "Kanchan",
  "Suddhodhan",
  "Gaidahawa",
  "Siyari",
  "Mayadevi",
  "Om Satiya",
  "Rohini",
  "Kotahimai",
  "Sammarimai",
  "Marchawari",
  "Shivaraj",
  "Buddhabhumi",
  "Banganga",
  "Krishnanagar",
  "Maharajganj",
  "Kapilbastu",
  "Bijayanagar",
  "Yasodhara",
  "Shuddhodhan",
  "Bhumikasthan",
  "Sandhikharka",
  "Shitaganga",
  "Malarani",
  "Chhatradev",
  "Panini",
  "Musikot",
  "Resunga",
  "Madane",
  "Dhurkot",
  "Isma",
  "Gulmi Durbar",
  "Chandrakot",
  "Chhatrakot",
  "Ruruchhetra",
  "Satyawoti",
  "Kali Gandaki",
  "Sisne",
  "Putha Uttanganga",
  "Bhoome",
  "Rolpa",
  "Gangadev",
  "Pariwartan",
  "Thawang",
  "Sunchhahari",
  "Tribeni",
  "Sunil Smriti",
  "Lungri",
  "Runtigadhi",
  "Sworgadwari",
  "Pyuthan",
  "Naubahini",
  "Gaumukhi",
  "Jhimaruk",
  "Mandavi",
  "Mallarani",
  "Sarumarani",
  "Aairawati",
  "Tulsipur",
  "Ghorahi",
  "Lamahi",
  "Babai",
  "Dangisharan",
  "Shantinagar",
  "Bangalachuli",
  "Gadhawa",
  "Nepalganj",
  "Kohalpur",
  "Khajura",
  "Baijanath",
  "Janaki",
  "Duduwa",
  "Rapti Sonari",
  "Narainapur",
  "Rajapur",
  "Madhuwan",
  "Thakurbaba",
  "Gulariya",
  "Barbardiya",
  "Bansgadhi",
  "Geruwa",
  "Badhaiyatal",
  "Bardiya",
  "Aathabisakot",
  "Chaurjahari",
  "Sanibheri",
  "Banphikot",
  "Banagad Kupinde",
  "Bagachour",
  "Sharada",
  "Kumakh",
  "Darma",
  "Siddha Kumakh",
  "Kalimati",
  "Chhatreshwori",
  "Kapurkot",
  "Panchapuri",
  "Bheriganga",
  "Birendranagar",
  "Lekabeshi",
  "Gurbhakot",
  "Chaukune",
  "Barahatal",
  "Chingad",
  "Simta",
  "Chhedagad",
  "Bheri Malika",
  "Nalgad",
  "Junichande",
  "Kuse",
  "Barekot",
  "Shivalaya",
  "Aathbis",
  "Chamunda Bindrasaini",
  "Dullu",
  "Narayan",
  "Thantikandh",
  "Bhairabi",
  "Mahabu",
  "Naumule",
  "Gurans",
  "Dungeshwor",
  "Bhagawatimai",
  "Thulibheri",
  "Shey Phoksundo",
  "Jagadulla",
  "Dolpo Buddha",
  "Mudkechula",
  "Kaike",
  "Chharka Tangsong",
  "Chandannath",
  "Kanaka Sundari",
  "Sinja",
  "Patarasi",
  "Hima",
  "Tila",
  "Tatopani",
  "Guthichaur",
  "Raskot",
  "Khandachakra",
  "Tilagupha",
  "Naraharinath",
  "Sanni Tribeni",
  "Pachal Jharana",
  "Palata",
  "Shuva Kalika",
  "Mahawai",
  "Chhayanath Rara",
  "Khatyad",
  "Soru",
  "Mugumakarmarog",
  "Namkha",
  "Simkot",
  "Kharpunath",
  "Sarkegad",
  "Chankheli",
  "Tanjakot",
  "Adanchuli",
  "Bungal",
  "Jayaprithbi",
  "Saipal",
  "Surma",
  "Talkot",
  "Bitthadchir",
  "Kedarsyun",
  "Durgathali",
  "Chhabis Pathibhara",
  "Masta",
  "Thalara",
  "Khaptad Chhanna",
  "Khaptad",
  "Budhinanda",
  "Badimalika",
  "Himali",
  "Gaumul",
  "Khaptad Chhededaha",
  "Jagannath",
  "Swamikartik Khapar",
  "Sanphebagar",
  "Mangalsen",
  "Kamal bazar",
  "Panchdebal Binayak",
  "Chaurpati",
  "Mellekh",
  "Bannigadhi Jayagadh",
  "Ramaroshan",
  "Dhakari",
  "Turmakhand",
  "Shikhar",
  "Dipayal Silgadhi",
  "Aadarsha",
  "Sayal",
  "Purbichouki",
  "Jorayal",
  "K.I. Singh",
  "Badi Kedar",
  "Bogatan Phudsil",
  "Dhangadhi",
  "Gauriganga",
  "Ghodaghodi",
  "Bhajani",
  "Tikapur",
  "Lamki Chuha",
  "Chure",
  "Kailari",
  "Mohanyal",
  "Joshipur",
  "Bardagoriya",
  "Dodhara Chandani",
  "Bhimdatta",
  "Bedkot",
  "Shuklaphanta",
  "Krishnapur",
  "Belouri",
  "Punarbas",
  "Beldandi",
  "Laljhadi",
  "Parashuram",
  "Amargadhi",
  "Bhageshwor",
  "Ajayameru",
  "Nawadurga",
  "Aalital",
  "Ganyapdhura",
  "Dasharathchand",
  "Puchaundi",
  "Melauli",
  "Patan",
  "Dilasaini",
  "Dogada Kedar",
  "Surnaya",
  "Pancheshwor",
  "Shivanath",
  "Sigas",
  "Mahakali",
  "Shailyashikhar",
  "Duhun",
  "Apihimal",
  "Malikarjun",
  "Naugad",
  "Lekam",
  "Marma",
];

const legacyWardNumberOptions = Array.from(
  { length: 35 },
  (_, index) => String(index + 1)
);

const municipalityWardNumbers =
  municipalityWardNumbersData as Record<string, string[]>;

const normalizeMunicipalityKey = (value: string) =>
  value
    .toLowerCase()
    .replace(/\s+/g, " ")
    .replace(/[–—]/g, "-")
    .trim();

const normalizedWardNumbers = new Map(
  Object.entries(municipalityWardNumbers).map(([name, wards]) => [
    normalizeMunicipalityKey(name),
    wards,
  ])
);

export const municipalityByDistrict =
  municipalityByDistrictData as Record<string, string[]>;

export const districtOptions =
  Object.keys(municipalityByDistrict).length > 0
    ? Object.keys(municipalityByDistrict).sort()
    : legacyDistrictOptions;

export const municipalityOptions = Array.from(
  new Set(
    Object.values(municipalityByDistrict).flat().length > 0
      ? Object.values(municipalityByDistrict).flat()
      : legacyMunicipalityOptions
  )
).sort();

export const wardNumberOptions = legacyWardNumberOptions;

export const getWardNumberOptions = (municipality?: string) => {
  if (!municipality) return [] as string[];
  return (
    municipalityWardNumbers[municipality] ??
    normalizedWardNumbers.get(normalizeMunicipalityKey(municipality)) ??
    legacyWardNumberOptions
  );
};
